# Generated by Django 4.0.5 on 2022-07-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_dates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dates',
            new_name='date',
        ),
    ]
