# Generated by Django 4.0.5 on 2022-07-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_rename_dates_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='heading',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
