# Generated by Django 4.0.5 on 2022-10-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_date_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='heading',
        ),
    ]
